student_count = 9
#First we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "ecomba"
puts "stephenlloyd"
puts "alexpeattie"
puts "vic329"
puts "NicolePell"
puts "bmordan"
puts "elenagarrone"
puts "yvettecook"
puts "HatStephens"
puts "ananogal"
puts "craigh44"
puts "Scully87"
puts "EllaNancyFay"
puts "fadieh"
puts "mala23"
puts "zrasool88"
puts "galicians"
puts "danjocutler"
puts "camillavk"
puts "MadameSardine"
puts "jamesascarter"
puts "slstevens"
puts "Schlap"
puts "andrewhercules"
puts "shortynielsen"
puts "snozza"
puts "SBLLB"
puts "annaschechter"
puts "alexfakhri"
puts "deniseyu"
puts "AndrewHarrison"
#Finally, we print the total
print "Overall, we have "
#It's important to know, that print() does not add a line break
print student_count
puts " great students"